const fs = require('fs');
const path = require('path');
const { buildMenu } = require('./menu-utils');

const shellRoot = __dirname;
const outputPath = path.join(shellRoot, 'menu-data.js');
const menu = buildMenu(shellRoot);

const content = [
  '// Generated by `node shell/generate-menu.js`.',
  '// Do not edit this file directly; add/remove files in ADM-* directories and regenerate.',
  `window.SHELL_MENU = ${JSON.stringify(menu, null, 2)};`,
  '',
].join('\n');

fs.writeFileSync(outputPath, content, 'utf8');
console.log(`Generated ${path.relative(process.cwd(), outputPath)} with ${menu.reduce((sum, group) => sum + group.items.length, 0)} menu items.`);
